feat: added configuration generation script

diff --git a/.github/workflows/validate-schema.yml b/.github/workflows/validate-schema.yml
--- a/.github/workflows/validate-schema.yml
+++ b/.github/workflows/validate-schema.yml
@@ -1,20 +1,8 @@
-name: "Validate Schema"
+name: "Update Configuration"
 
 on:
   workflow_dispatch:
-    inputs:
-      stateId:
-        description: "State Id"
-      eventName:
-        description: "Event Name"
-      eventPayload:
-        description: "Event Payload"
-      settings:
-        description: "Settings"
-      authToken:
-        description: "Auth Token"
-      ref:
-        description: "Ref"
+  push:
 
 jobs:
   validate:
@@ -30,9 +18,21 @@ jobs:
         with:
           node-version: "20.10.0"
 
-      - name: Install deps and run validation
+      - name: Install deps and run configuration update
         run: |
           yarn install --immutable --immutable-cache --check-cache
-          yarn tsx src/validate-schema.ts
+          yarn tsx src/update-configuration.ts
+
+      - name: Commit and Push generated types
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git add ./manifest.json
+          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
+            git commit -m "chore: updated generated configuration" || echo "Lint-staged check failed"
+            git push origin HEAD:${{ github.ref_name }}
+          else
+            echo "No changes to commit"
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
